### ISSUE TITLE
No frontend

### ISSUE THREAD

**Issue by Imran-imtiaz48** [ALIPE-Official/BiSyllab-Web-Design#2]
Please share the website link. Current website link is not working with me.

**Comment by andrefelipebarros** [comment]
Unfortunately the link is not working due to the hosting expiry date.

I'll sort it out, thanks for the heads up.

**Comment by andrefelipebarros** [comment]
New Link: https://andrefelipebarros.github.io/BiSyllab-Web-Design/ 
😁
